FREAKS = {
'blasterball': {'NAME': 'Blasteraball','INFO': 'Nave regular que segue um caminho pre-definido.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'metalrocket': {'NAME': 'Blaze','INFO': 'Vai até a sua direção atirando.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Queimar','',0]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'centuryhawk': {'NAME': 'Slime','INFO': 'Faz curvas pela tela para te alcançar.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Gosma','',1]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'rotatorydriller': {'NAME': 'Slime','INFO': 'Vai de uma lateral até a outra.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Gosma','',1]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'spiralship': {'NAME': 'Slime','INFO': 'Segue um caminho ondulado até a sua direção.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Gosma','',1]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'laserray': {'NAME': 'Rock','INFO': 'Atira um raio laser após travar em sua posição.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'redbomb': {'NAME': 'Redbomb','INFO': 'explode após um tempo determinado na tela.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'eggbomb': {'NAME': 'Eggbomb','INFO': 'Libera diversos tiros após tempo determinado;',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'blade': {'NAME': 'Eggbomb','INFO': 'Uma lâmina dentada que ricocheteia tiros e destrói naves.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'jetflames': {'NAME': 'Eggbomb','INFO': 'Solta um jato de fogo durante um intervalo de tempo.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'mirrorstroop': {'NAME': 'Eggbomb','INFO': 'Protegidas por escudos espelhados, você precisa atirar no momento certo.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'wallballcannon': {'NAME': 'Eggbomb','INFO': 'Fica grudado nas paredes e tira em você',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'torpedeiro': {'NAME': 'Eggbomb','INFO': 'Lança mísseis teleguiados.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'thundertower': {'NAME': 'Eggbomb','INFO': 'Lança raios elétricos na horizontal e sobe desce para seguir sua posição.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'landrover': {'NAME': 'Eggbomb','INFO': 'Corre pelo solo do planeta e atira em sua direção',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'heavyship': {'NAME': 'Eggbomb','INFO': 'Aguenta mais tiros do que uma nave convencional.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'navemissel': {'NAME': 'Eggbomb','INFO': 'Voa jogando mísseis pelo caminho.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},


'spacedragon': {'NAME': 'Eggbomb','INFO': 'Boss dragão de spitti',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'sateliteship': {'NAME': 'Eggbomb','INFO': 'Nave com oito canhões girando em volta dele',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'bladeship': {'NAME': 'Eggbomb','INFO': 'Nave portando dois braços com lâminas dentadas.',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'spacetruck': {'NAME': 'Eggbomb','INFO': 'Caminhão com canhões',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'submarineship': {'NAME': 'Eggbomb','INFO': 'Nave espacial híbrida com submarino',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'battlerobot': {'NAME': 'Eggbomb','INFO': 'Robô gigante com canhões',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'najjmathowhale': {'NAME': 'Eggbomb','INFO': 'Baleia de fogo',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'sneezaworm': {'NAME': 'Eggbomb','INFO': 'Minhoca gigante',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'Mothership': {'NAME': 'Eggbomb','INFO': 'Sub-boss final',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},

'Outofthisdimension': {'NAME': 'Eggbomb','INFO': 'Boss final',
'HEIGHT': '1,20','HABITAT': None,'TYPE': None,
'STRENGHT': 2,'AGILITY': 5,'RESISTANCE': 0,'VITALITY': 1,'PATH': 'maze1','DODGE': None,
'HABILITIES': [['Atirar','',2]],
'FOOD': None,'WEAKNESS': None,'BLOOD': 0,'ITEM': None,'SONG': None,'SCREAM': None},
}

ITEMS = {
'parts': {'NAME': 'peças','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': 0},
'stellar_star': {'NAME': 'estrela estelar','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': 0},

'reactor0': {'NAME': 'reator vazio','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,
	'PROPERTIES': {'SPACING': 0,'SPEED': 0,'ANGLE': 0,'MISSPD': 0,'MISSACC': 0}},
'reactor1': {'NAME': 'reator de plasma','DESCRIPTION': '','PRICE': 10,'VOLUME': 0,'WEIGHT': 0,
	'PROPERTIES': {'SPACING': 40,'SPEED': 8,'ANGLE': 1,'MISSPD': 1.5,'MISSACC': 0.1,'LASERSIZE': 10}},
'reactor2': {'NAME': 'reator de combustão','DESCRIPTION': '','PRICE': 25,'VOLUME': 0,'WEIGHT': 0,
	'PROPERTIES': {'SPACING': 60,'SPEED': 7,'ANGLE': 2,'MISSPD': 7,'MISSACC': 0,'FLAMEFADE': 0.4,'FLAMESPD': 5}},
'reactor3': {'NAME': 'reator de bolha','DESCRIPTION': '','PRICE': 50,'VOLUME': 0,'WEIGHT': 0,
	'PROPERTIES': {'SPACING': 20,'SPEED': 6,'ANGLE': 0.5,'MISSPD': 6,'MISSACC': 0}},
'reactor4': {'NAME': 'reator de cristais','DESCRIPTION': '','PRICE': 120,'VOLUME': 0,'WEIGHT': 0,
	'PROPERTIES': {'SPACING': 0,'SPEED': 9,'ANGLE': 0,'MISSPD': 9,'MISSACC': 0}},
'reactor5': {'NAME': 'reator de ondas','DESCRIPTION': '','PRICE': 250,'VOLUME': 0,'WEIGHT': 0,
	'PROPERTIES': {'SPACING': 0,'SPEED': 5,'ANGLE': 0,'MISSPD': 5,'MISSACC': 0}},
'reactor6': {'NAME': 'reator de eletricidade','DESCRIPTION': '','PRICE': 500,'VOLUME': 0,'WEIGHT': 0,
	'PROPERTIES': {'SPACING': 80,'SPEED': 10,'ANGLE': 3,'MISSPD': 2,'MISSACC': 0}},
'reactor7': {'NAME': 'reator estelar','DESCRIPTION': '','PRICE': 1200,'VOLUME': 0,'WEIGHT': 0,
	'PROPERTIES': {'SPACING': 0,'SPEED': 12,'WAVE': 3,'MISSPD': 0,'MISSACC': 0}},

'shield_regular': {'NAME': 'escudo regular','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 0}},
'shield_armored': {'NAME': 'escudo blindado','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 1}},
'shield_fortified': {'NAME': 'escudo fortificado','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 2}},
'shield_shrink': {'NAME': 'escudo encolhedor','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 0,'LIFE': 2,'SIZE': 3}},
'shield_refractor': {'NAME': 'escudo refrator','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 1}},
'shield_strong': {'NAME': 'escudo resistente','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 0,'LIFE': 5}},
'shield_phantom': {'NAME': 'escudo fantasma','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 3}},
'shield_ricochet': {'NAME': 'escudo ricochete','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 1,'BOUNCE': 0}},
'shield_floater': {'NAME': 'escudo bóia','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 2,'BOUCE': 1}},
'shield_invencibility': {'NAME': 'escudo invencível','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'PROTECTION': 3,'DAMAGE': 5555,'TIME': 120}},

'bomb_regular': {'NAME': 'bomba atômica','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000}},
'bomb_cyclone': {'NAME': 'bomba de singularidade','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'ATRACTION': 10}},
'bomb_eletric': {'NAME': 'bomba de eletricidade','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'PAUSE': 0}},
'bomb_wave': {'NAME': 'bomba eletromagnética','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'ATRACTION': -10}},
'bomb_paralyzing': {'NAME': 'bomba paralizante','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'PAUSE': 1}},
'bomb_poisoning': {'NAME': 'bomba radioativa','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'POISON': 2}},
'bomb_slowtime': {'NAME': 'bomba da relatividade','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'PAUSE': 2}},
'bomb_sniper': {'NAME': 'bomba morte súbita','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000}},
'bomb_flaming': {'NAME': 'bomba de plasma','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'DETONATE': 60,'ROTATE': 1,'SIZE': 3}},
'bomb_quake': {'NAME': 'bomba de tremor','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'QUAKE': 5}},
'bomb_rage': {'NAME': 'bomba furiosa','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000}},
'bomb_selection': {'NAME': 'bomba seletora','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'TARGET': 0}},
'bomb_timed': {'NAME': 'bomba relógio','DESCRIPTION': '','PRICE': 0,'VOLUME': 0,'WEIGHT': 0,'PROPERTIES': {'EXPLOSION': 2000,'DETONATE': 60}},
}

AVATAR = {
'spaceship_base': ['mandíbula','escaravelho','redondo','pontudo'],
'spaceship_wing': ['para trás','pontudo','propulsores','duplo','redondo','plano','caça'],
'spaceship_cockpit': ['redondo','estreito','duplo','janela'],
'spaceship_spoiler': ['duplo','traseiro','pequeno','nenhum'],
'spaceship_propulsor': ['convencional'],
'spaceship_texture': ['nenhum'],
}

MENU = {'spaceship_base': 'calota','spaceship_wing': 'asas','spaceship_cockpit': 'cabine','spaceship_spoiler': 'spoiler',
	'spaceship_propulsor': 'propulsor','spaceship_texture': 'textura','spaceship_stickers': 'adesivos'}