<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" name="grafitti" tilewidth="30" tileheight="30" rows="6" columns="8">
 <img source="../grafitti.png" width="180" height="240"/>
 <tile id="0" type="street"/>
 <tile id="1" type="crossing"/>
 <tile id="2" type="crossing"/>
 <tile id="3" type="sidewalk"/>
 <tile id="4" type="sidewalk"/>
 <tile id="5" type="brick"/>
 <tile id="6" type="brick"/>
 <tile id="7" type="wall"/>
 <tile id="8" type="wall"/>
 <tile id="9" type="wall"/>
 <tile id="10" type="wall"/>
 <tile id="11" type="wall"/>
 <tile id="12" type="wall"/>
 <tile id="13" type="street"/>
 <tile id="14" type="street"/>
 <tile id="15" type="street"/>
 <tile id="16" type="sidewalk"/>
 <tile id="17" type="sidewalk"/>
 <tile id="18" type="brick"/>
 <tile id="19" type="brick"/>
 <tile id="20" type="wall"/>
 <tile id="21" type="wall"/>
 <tile id="22" type="wall"/>
 <tile id="23" type="wall"/>
 <tile id="24" type="wall"/>
 <tile id="25" type="wall"/>
 <tile id="26" type="street"/>
 <tile id="27" type="street"/>
 <tile id="28" type="street"/>
 <tile id="29" type="street"/>
 <tile id="30" type="sidewalk"/>
 <tile id="31" type="brick"/>
 <tile id="35" type="wall"/>
 <tile id="36" type="wall"/>
 <tile id="37" type="wall"/>
 <tile id="38" type="wall"/>
 <tile id="39" type="street"/>
 <tile id="40" type="street"/>
 <tile id="41" type="street"/>
 <tile id="42" type="street"/>
 <tile id="43" type="street"/>
 <tile id="44" type="street"/>
 <tile id="45" type="street"/>
 <tile id="46" type="street"/>
 <tile id="47" type="street"/>
</tileset>
